[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/bugtrack-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"